// Package types provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.8.1 DO NOT EDIT.
package types

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Code defines model for Code.
type Code string

// Redirect defines model for Redirect.
type Redirect struct {
	Hits         int32     `json:"hits"`
	Id           string    `json:"id"`
	RedirectCode Code      `json:"redirectCode"`
	TimeCreated  time.Time `json:"timeCreated"`
	Url          URL       `json:"url"`
}

// RedirectArray defines model for RedirectArray.
type RedirectArray []Redirect

// URL defines model for URL.
type URL string

// User defines model for User.
type User struct {
	Email            openapi_types.Email `json:"email"`
	Id               string              `json:"id"`
	Name             string              `json:"name"`
	RedirectsCreated RedirectArray       `json:"redirectsCreated"`
}

// UserPost defines model for UserPost.
type UserPost struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`
}

// N200RedirectFound defines model for 200RedirectFound.
type N200RedirectFound Redirect

// N200UserFound defines model for 200UserFound.
type N200UserFound User

// GetRedirectByCodeParams defines parameters for GetRedirectByCode.
type GetRedirectByCodeParams struct {
	RedirectCode *Code `json:"redirectCode,omitempty"`
}

// CreateRedirectParams defines parameters for CreateRedirect.
type CreateRedirectParams struct {
	Url *URL `json:"url,omitempty"`
}

// CreateRedirectsBatchJSONBody defines parameters for CreateRedirectsBatch.
type CreateRedirectsBatchJSONBody []URL

// GetRedirectsBatchJSONBody defines parameters for GetRedirectsBatch.
type GetRedirectsBatchJSONBody RedirectArray

// GetUserByEmailParams defines parameters for GetUserByEmail.
type GetUserByEmailParams struct {
	Email *openapi_types.Email `json:"email,omitempty"`
}

// CreateUserJSONBody defines parameters for CreateUser.
type CreateUserJSONBody UserPost

// AppendToUserRedirectsJSONBody defines parameters for AppendToUserRedirects.
type AppendToUserRedirectsJSONBody Redirect

// SetUserRedirectsJSONBody defines parameters for SetUserRedirects.
type SetUserRedirectsJSONBody []Redirect

// CreateRedirectsBatchJSONRequestBody defines body for CreateRedirectsBatch for application/json ContentType.
type CreateRedirectsBatchJSONRequestBody CreateRedirectsBatchJSONBody

// GetRedirectsBatchJSONRequestBody defines body for GetRedirectsBatch for application/json ContentType.
type GetRedirectsBatchJSONRequestBody GetRedirectsBatchJSONBody

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody CreateUserJSONBody

// AppendToUserRedirectsJSONRequestBody defines body for AppendToUserRedirects for application/json ContentType.
type AppendToUserRedirectsJSONRequestBody AppendToUserRedirectsJSONBody

// SetUserRedirectsJSONRequestBody defines body for SetUserRedirects for application/json ContentType.
type SetUserRedirectsJSONRequestBody SetUserRedirectsJSONBody
